# Site settings
title: Umbraco Package Ideas
description: Open ideas for Umbraco community packages
baseurl: "/umbraco-package-ideas/"
url: ""
exclude: ["CONTRIBUTING.md", "LICENSE.md", "README.md", "TODO.md", "Gemfile.lock", "Gemfile"]

# collections
collections:
  categories:
    output: true
    permalink: /:categories/index.html
  ideas:
    output: true
    permalink: /:categories/:name

# Build settings
github: [metadata]
repository: leekelleher/umbraco-package-ideas
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-gist
  - jekyll-octicons
  - jemoji
